# Generated by Django 2.2.2 on 2019-10-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='message',
        ),
    ]
