# Generated by Django 2.2.2 on 2019-10-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_member_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
