# Generated by Django 2.2.2 on 2019-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
