# Generated by Django 2.2.2 on 2019-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191018_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.CharField(default='00228 96273390', max_length=15),
        ),
    ]
